;;; anki-target-sync-test.el --- Host registration sync integration -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'imoogi)

(defmacro imoogi-target-sync-test--with-files (&rest body)
  (declare (indent 0))
  `(let* ((base (make-temp-file "imoogi-target-sync-" t))
          (imoogi-targets-file (expand-file-name "host/targets.json" base))
          (imoogi-sync-root nil)
          (imoogi-exclude-patterns nil)
          (imoogi-binary-path (executable-find "true")))
     (unwind-protect (progn ,@body)
       (dolist (buffer (buffer-list))
         (when-let* ((file (buffer-file-name buffer)))
           (when (file-in-directory-p file base)
             (with-current-buffer buffer (set-buffer-modified-p nil))
             (kill-buffer buffer))))
       (delete-directory base t))))

(defun imoogi-target-sync-test--file (base relative &optional id)
  (let ((file (expand-file-name relative base)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (insert "* Card\n:PROPERTIES:\n:ANKI_NOTE_TYPE: Basic\n")
      (when id (insert (format ":ANKI_NOTE_ID: %d\n" id)))
      (insert ":END:\nAnswer\n"))
    file))

(ert-deftest imoogi-target-sync-unions-legacy-folders-and-one-file-with-writeback ()
  (imoogi-target-sync-test--with-files
   (let* ((legacy-file (imoogi-target-sync-test--file base "legacy/note.org"))
          (folder-file (imoogi-target-sync-test--file base "folder/deep/note.org"))
          (single (imoogi-target-sync-test--file base "loose/note.org"))
          (_sibling (imoogi-target-sync-test--file base "loose/untouched.org"))
          (imoogi-sync-root (file-name-directory legacy-file))
          (targets (list (list :kind 'directory :path (expand-file-name "folder" base))
                         (list :kind 'file :path single)
                         (list :kind 'file :path folder-file)))
          (next-id 100) requests)
     (cl-letf (((symbol-function 'imoogi-targets-load) (lambda () targets))
               ((symbol-function 'imoogi-process-run)
                (lambda (_binary config census entries)
                  (push (list config census entries) requests)
                  (list :ok t :errors nil
                        :results (mapcar (lambda (entry)
                                           (list :key (plist-get entry :key)
                                                 :action "added" :note-id (cl-incf next-id)))
                                         entries)))))
       (imoogi-sync))
     (should (= (length requests) 3))
     (should (= (apply #'+ (mapcar (lambda (request) (length (nth 2 request))) requests)) 3))
     (dolist (file (list legacy-file folder-file single))
       (with-temp-buffer
         (insert-file-contents file)
         (should (string-match-p ":ANKI_NOTE_ID: 10[1-3]" (buffer-string)))))
     (with-temp-buffer
       (insert-file-contents (expand-file-name "loose/untouched.org" base))
       (should-not (string-match-p "ANKI_NOTE_ID" (buffer-string))))
     (dolist (request requests)
       (let ((config (car request)))
         (if (file-equal-p (plist-get config :sync-root) imoogi-sync-root)
             (progn
               (should (plist-get config :scan-complete))
               (should (equal (plist-get config :registry-path)
                              (imoogi--registry-path (plist-get config :sync-root)))))
           (should-not (plist-get config :scan-complete))
           (should (file-in-directory-p (plist-get config :registry-path)
                                        (file-name-directory imoogi-targets-file)))))))))

(ert-deftest imoogi-target-sync-global-duplicates-never-reach-backend ()
  (imoogi-target-sync-test--with-files
    (let* ((one (imoogi-target-sync-test--file base "one/note.org" 42))
           (two (imoogi-target-sync-test--file base "two/note.org" 42))
           (imoogi-sync-root (file-name-directory one))
          (targets (mapcar (lambda (file) (list :kind 'file :path file)) (list one two)))
          requests report)
     (cl-letf (((symbol-function 'imoogi-targets-load) (lambda () targets))
               ((symbol-function 'imoogi-process-run)
                 (lambda (_binary config census entries)
                   (should-not entries)
                   (should-not census)
                   (should-not (plist-get config :scan-complete))
                  (push census requests)
                  (list :ok t :results nil :errors nil))))
       (setq report (imoogi-sync)))
     (should (= (length requests) 2))
     (should (string-match-p (regexp-quote (imoogi-error-message "note_id_duplicated")) report)))))

(ert-deftest imoogi-target-sync-missing-registration-suppresses-legacy-deletion ()
  (imoogi-target-sync-test--with-files
   (let* ((file (imoogi-target-sync-test--file base "legacy/note.org"))
          (imoogi-sync-root (file-name-directory file))
          (targets (list (list :kind 'file :path (expand-file-name "missing.org" base))))
          requests)
     (cl-letf (((symbol-function 'imoogi-targets-load) (lambda () targets))
               ((symbol-function 'imoogi-process-run)
                (lambda (_binary config _census _entries)
                  (should-not (plist-get config :scan-complete))
                  (push config requests)
                  (list :ok t :results nil :errors nil))))
       (should (string-match-p "missing.org" (imoogi-sync))))
     (should requests))))

;;; anki-target-sync-test.el ends here
