;;; org-setup-test.el --- Org directory setup tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(ert-deftest imoogi-org-setup-creates-directory-and-preserves-notes ()
  (let* ((home (make-temp-file "imoogi-org-home-" t))
         (notes (expand-file-name "notes/" home))
         (agenda (expand-file-name "agenda.org" notes))
         (org-directory "/previous/")
         (org-agenda-files nil)
         (expand (symbol-function 'expand-file-name)))
    (unwind-protect
        (cl-letf (((symbol-function 'expand-file-name)
                   (lambda (name &optional base)
                     (if (equal name "~/notes/") notes (funcall expand name base)))))
          (should (equal (imoogi-org-setup) notes))
          (should (file-directory-p notes))
          (should (file-directory-p (expand-file-name "permanent/" notes)))
          (should (file-exists-p agenda))
          (should (equal org-directory notes))
          (should (equal org-agenda-files (list notes)))
          (with-temp-file (concat notes "existing.org") (insert "* Keep me\n"))
          (with-temp-file agenda (insert "* Existing agenda\n"))
          (imoogi-org-setup)
          (should (equal (with-temp-buffer
                           (insert-file-contents agenda)
                           (buffer-string)) "* Existing agenda\n"))
          (should (equal (with-temp-buffer
                           (insert-file-contents (concat notes "existing.org"))
                           (buffer-string)) "* Keep me\n")))
      (delete-directory home t))))
(ert-deftest imoogi-org-setup-file-collision-preserves-setting ()
  (let* ((home (make-temp-file "imoogi-org-home-" t))
         (notes (expand-file-name "notes/" home))
         (org-directory "/previous/")
         (org-agenda-files nil)
         (expand (symbol-function 'expand-file-name)))
    (unwind-protect
        (progn
          (with-temp-file (directory-file-name notes) (insert "Keep"))
          (cl-letf (((symbol-function 'expand-file-name)
                     (lambda (name &optional base)
                       (if (equal name "~/notes/") notes (funcall expand name base)))))
            (should-error (imoogi-org-setup) :type 'file-error)
            (should (equal org-directory "/previous/"))
            (should-not org-agenda-files)))
      (delete-directory home t))))

(ert-deftest imoogi-org-setup-registers-notes-agenda-without-losing-existing-targets ()
  (let* ((home (make-temp-file "imoogi-org-home-" t))
         (old-directory (expand-file-name "old/" home))
         (notes (expand-file-name "notes/" home))
         (existing (expand-file-name "existing.org" old-directory))
         (nested (expand-file-name "nested/" notes))
         (org-directory old-directory)
         (org-agenda-files '("existing.org"))
         (expand (symbol-function 'expand-file-name)))
    (unwind-protect
        (progn
          (make-directory old-directory)
          (with-temp-file existing (insert "* Existing\n"))
          (cl-letf (((symbol-function 'expand-file-name)
                     (lambda (name &optional base)
                       (if (equal name "~/notes/") notes (funcall expand name base)))))
            (imoogi-org-setup)
            (with-temp-file (expand-file-name "daily.org" notes) (insert "* Daily\n"))
            (make-directory nested)
            (with-temp-file (expand-file-name "hidden.org" nested) (insert "* Hidden\n"))
            (let ((files (org-agenda-files)))
              (should (member existing files))
              (should (member (expand-file-name "agenda.org" notes) files))
              (should (member (expand-file-name "daily.org" notes) files))
              (should-not (member (expand-file-name "hidden.org" nested) files)))
            (should (equal org-agenda-files (list existing notes)))))
      (delete-directory home t))))

(ert-deftest imoogi-org-setup-agenda-file-collision-preserves-settings ()
  (let* ((home (make-temp-file "imoogi-org-home-" t))
         (notes (expand-file-name "notes/" home))
         (agenda (expand-file-name "agenda.org" notes))
         (org-directory "/previous/")
         (org-agenda-files '("/previous-agenda.org"))
         (expand (symbol-function 'expand-file-name)))
    (unwind-protect
        (progn
          (make-directory agenda t)
          (cl-letf (((symbol-function 'expand-file-name)
                     (lambda (name &optional base)
                       (if (equal name "~/notes/") notes (funcall expand name base)))))
            (should-error (imoogi-org-setup) :type 'file-error)
            (should (equal org-directory "/previous/"))
            (should (equal org-agenda-files '("/previous-agenda.org")))))
      (delete-directory home t))))

(ert-deftest imoogi-org-setup-preserves-string-storage-variable ()
  (let* ((home (make-temp-file "imoogi-org-home-" t))
         (notes (expand-file-name "notes/" home))
         (agenda-store (expand-file-name "agenda-files" home))
         (existing (expand-file-name "existing.org" home))
         (org-directory home)
         (org-agenda-files agenda-store)
         (expand (symbol-function 'expand-file-name)))
    (unwind-protect
        (progn
          (with-temp-file agenda-store (insert existing "\n"))
          (with-temp-file existing (insert "* Existing\n"))
          (cl-letf (((symbol-function 'expand-file-name)
                     (lambda (name &optional base)
                       (if (equal name "~/notes/") notes (funcall expand name base)))))
            (imoogi-org-setup))
          (should (equal org-agenda-files agenda-store))
          (should (equal (with-temp-buffer
                           (insert-file-contents agenda-store)
                           (buffer-string))
                         (concat existing "\n" notes "\n"))))
      (delete-directory home t))))

(ert-deftest imoogi-org-setup-keeps-modified-agenda-storage-buffer ()
  (let* ((home (make-temp-file "imoogi-org-home-" t))
         (notes (expand-file-name "notes/" home))
         (agenda-store (expand-file-name "agenda-files" home))
         (org-directory home)
         (org-agenda-files agenda-store)
         (expand (symbol-function 'expand-file-name))
         buffer)
    (unwind-protect
        (progn
          (with-temp-file agenda-store (insert "existing.org\n"))
          (setq buffer (find-file-noselect agenda-store))
          (with-current-buffer buffer
            (goto-char (point-max))
            (insert "unsaved.org\n"))
          (cl-letf (((symbol-function 'expand-file-name)
                     (lambda (name &optional base)
                       (if (equal name "~/notes/") notes (funcall expand name base)))))
            (should-error (imoogi-org-setup) :type 'user-error))
          (should (buffer-live-p buffer))
          (with-current-buffer buffer
            (should (buffer-modified-p))
            (should (string-match-p "unsaved.org" (buffer-string))))
          (should (equal org-directory home))
          (should (equal org-agenda-files agenda-store))
          (should (equal (with-temp-buffer
                           (insert-file-contents agenda-store)
                           (buffer-string))
                         "existing.org\n")))
      (when (buffer-live-p buffer)
        (with-current-buffer buffer
          (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-directory home t))))

(ert-deftest imoogi-org-setup-doctor-copies-flat-notes-without-deleting-or-overwriting ()
  (let* ((home (make-temp-file "imoogi-org-doctor-" t))
         (notes (expand-file-name "notes/" home))
         (permanent (expand-file-name "permanent/" notes))
         (legacy (expand-file-name "legacy.org" notes))
         (agenda (expand-file-name "agenda.org" notes))
         (scratch (expand-file-name "scratch.org" notes))
         (existing (expand-file-name "existing.org" notes))
         (existing-target (expand-file-name "existing.org" permanent))
         (org-directory nil)
         (org-agenda-files nil)
         (expand (symbol-function 'expand-file-name)))
    (unwind-protect
        (progn
          (make-directory permanent t)
          (with-temp-file legacy (insert "#+title: Legacy\n\n* Keep\n"))
          (with-temp-file agenda (insert "* Agenda\n"))
          (with-temp-file scratch (insert "* Scratch\n"))
          (with-temp-file existing (insert "* New source\n"))
          (with-temp-file existing-target (insert "* Keep destination\n"))
          (cl-letf (((symbol-function 'expand-file-name)
                     (lambda (name &optional base)
                       (if (equal name "~/notes/") notes (funcall expand name base))))
                    ((symbol-function 'org-roam-db-sync) (lambda () nil)))
            (let ((result (imoogi-org-setup-doctor)))
              (should (= (plist-get result :copied) 1))
              (should (= (plist-get result :skipped) 1))
              (should (= (plist-get result :excluded) 2))))
          (should (file-exists-p legacy))
          (should (file-exists-p agenda))
          (should (file-exists-p scratch))
          (should (equal (with-temp-buffer
                           (insert-file-contents (expand-file-name "legacy.org" permanent))
                           (buffer-string))
                         "#+title: Legacy\n\n* Keep\n"))
          (should (equal (with-temp-buffer
                           (insert-file-contents existing-target)
                           (buffer-string))
                         "* Keep destination\n")))
      (delete-directory home t))))

(ert-deftest imoogi-org-setup-doctor-is-idempotent ()
  (let* ((home (make-temp-file "imoogi-org-doctor-" t))
         (notes (expand-file-name "notes/" home))
         (legacy (expand-file-name "legacy.org" notes))
         (org-directory nil)
         (org-agenda-files nil)
         (expand (symbol-function 'expand-file-name)))
    (unwind-protect
        (progn
          (make-directory notes t)
          (with-temp-file legacy (insert "* Original\n"))
          (cl-letf (((symbol-function 'expand-file-name)
                     (lambda (name &optional base)
                       (if (equal name "~/notes/") notes (funcall expand name base))))
                    ((symbol-function 'org-roam-db-sync) (lambda () nil)))
            (imoogi-org-setup-doctor)
            (with-temp-file legacy (insert "* Changed source\n"))
            (let ((result (imoogi-org-setup-doctor)))
              (should (= (plist-get result :copied) 0))
              (should (= (plist-get result :skipped) 1))))
          (should (equal (with-temp-buffer
                           (insert-file-contents
                            (expand-file-name "legacy.org"
                                              (expand-file-name "permanent/" notes)))
                           (buffer-string))
                         "* Original\n")))
      (delete-directory home t))))
