;;; treemacs-tool-window-test.el --- IntelliJ-style Treemacs tool window tests -*- lexical-binding: t; -*-

;;; Code:

(require 'bookmark)
(require 'button)
(require 'cl-lib)
(require 'ert)
(require 'imenu)

(ert-deftest imoogi-treemacs-file-tree-is-bound-at-s-1 ()
  (should (eq (lookup-key global-map (kbd "s-1"))
              #'imoogi-treemacs-toggle-file-tree)))

(ert-deftest imoogi-treemacs-file-tree-has-intellij-focus-bindings ()
  (require 'treemacs)
  (should (eq (lookup-key treemacs-mode-map (kbd "s-1"))
              #'imoogi-treemacs-toggle-file-tree))
  (should (eq (lookup-key treemacs-mode-map (kbd "<escape>"))
              #'treemacs-select-window))
  (should (eq treemacs-select-when-already-in-treemacs 'move-back)))

(ert-deftest imoogi-treemacs-file-tree-wrapper-is-bound-at-C-x-t-t ()
  (should (eq (lookup-key global-map (kbd "C-x t t"))
              #'imoogi-treemacs-toggle-file-tree)))

;; @MX:NOTE transient-get-suffix 의 반환 형태에 의존한다
;; ((transient-suffix :key ... :command CMD) 의 cdr 이 plist). 향후 transient
;; 업그레이드로 형태가 바뀌면 (get 'imoogi-transient-master 'transient--layout)
;; 를 직접 들여다보는 방식으로 대체한다 (research.md §4.1).
(ert-deftest imoogi-treemacs-file-tree-wrapper-is-used-by-master-transient ()
  (should (eq (plist-get (cdr (transient-get-suffix 'imoogi-transient-master "t"))
                         :command)
              #'imoogi-treemacs-toggle-file-tree)))

(ert-deftest imoogi-treemacs-uses-colorful-nerd-icons-theme ()
  (require 'treemacs)
  (should (equal doom-themes-treemacs-theme "doom-colors"))
  (should (equal (treemacs-theme->name treemacs--current-theme)
                 "doom-colors")))

(ert-deftest imoogi-treemacs-bookmarks-is-bound-at-s-2 ()
  (should (eq (lookup-key global-map (kbd "s-2"))
              #'imoogi-treemacs-toggle-bookmarks)))

(ert-deftest imoogi-treemacs-structure-is-bound-at-s-7 ()
  (should (eq (lookup-key global-map (kbd "s-7"))
              #'imoogi-treemacs-toggle-structure)))

(ert-deftest imoogi-treemacs-file-tree-closes-when-focused ()
  (let ((closed nil)
        (selected nil)
        (treemacs-window (selected-window)))
    (cl-letf (((symbol-function 'treemacs-get-local-window)
               (lambda () treemacs-window))
              ((symbol-function 'treemacs-quit)
               (lambda ()
                 (setq closed t)))
              ((symbol-function 'treemacs-select-window)
               (lambda (&optional _arg)
                 (setq selected t))))
      (imoogi-treemacs-toggle-file-tree)
      (should closed)
      (should-not selected))))

(ert-deftest imoogi-treemacs-file-tree-focuses-when-visible-from-editor ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((editor-window (selected-window))
           (treemacs-window (split-window-right))
           (closed nil))
      (cl-letf (((symbol-function 'treemacs-get-local-window)
                 (lambda () treemacs-window))
                ((symbol-function 'treemacs-quit)
                 (lambda ()
                   (setq closed t)))
                ((symbol-function 'treemacs-select-window)
                 (lambda (&optional _arg)
                   (select-window treemacs-window))))
        (select-window editor-window)
        (imoogi-treemacs-toggle-file-tree)
        (should (eq (selected-window) treemacs-window))
        (should-not closed)))))

(ert-deftest imoogi-treemacs-file-tree-shows-when-absent ()
  (let ((hidden nil)
        (shown nil))
    (cl-letf (((symbol-function 'treemacs-get-local-window)
               (lambda () nil))
              ((symbol-function 'imoogi-treemacs-hide-tool-window)
               (lambda ()
                 (setq hidden t)))
              ((symbol-function 'treemacs-select-window)
               (lambda (&optional _arg)
                 (setq shown t))))
      (imoogi-treemacs-toggle-file-tree)
      (should hidden)
      (should shown))))

(ert-deftest imoogi-treemacs-bookmarks-hide-when-bookmarks-visible ()
  (let ((bookmarks-window (selected-window))
        (deleted-window nil)
        (hidden nil)
        (rendered nil)
        (displayed nil))
    (cl-letf (((symbol-function 'imoogi-treemacs--custom-tool-window)
               (lambda (kind)
                 (and (eq kind 'bookmarks) bookmarks-window)))
              ((symbol-function 'delete-window)
               (lambda (window)
                 (setq deleted-window window)))
              ((symbol-function 'imoogi-treemacs-hide-tool-window)
               (lambda ()
                 (setq hidden t)))
              ((symbol-function 'imoogi-treemacs--render-bookmarks)
               (lambda (&rest _)
                 (setq rendered t)))
              ((symbol-function 'imoogi-treemacs--display-tool-buffer)
               (lambda (&rest _)
                 (setq displayed t))))
      (imoogi-treemacs-toggle-bookmarks)
      (should (eq deleted-window bookmarks-window))
      (should-not hidden)
      (should-not rendered)
      (should-not displayed))))

(ert-deftest imoogi-treemacs-bookmarks-switches-from-another-tool-window ()
  (let ((hidden nil)
        (rendered nil)
        (displayed nil)
        (source-buffer (current-buffer))
        (display-kind nil))
    (cl-letf (((symbol-function 'imoogi-treemacs--custom-tool-window)
               (lambda (_kind) nil))
              ((symbol-function 'imoogi-treemacs--editor-buffer)
               (lambda () source-buffer))
              ((symbol-function 'imoogi-treemacs-hide-tool-window)
               (lambda ()
                 (setq hidden t)))
              ((symbol-function 'imoogi-treemacs--render-bookmarks)
               (lambda (_buffer seen-source-buffer)
                 (setq rendered seen-source-buffer)))
              ((symbol-function 'imoogi-treemacs--display-tool-buffer)
               (lambda (_buffer kind)
                 (setq displayed t
                       display-kind kind))))
      (imoogi-treemacs-toggle-bookmarks)
      (should hidden)
      (should (eq rendered source-buffer))
      (should displayed)
      (should (eq display-kind 'bookmarks)))))

(ert-deftest imoogi-treemacs-structure-hide-when-structure-visible ()
  (let ((structure-window (selected-window))
        (deleted-window nil)
        (hidden nil)
        (rendered nil)
        (displayed nil))
    (cl-letf (((symbol-function 'imoogi-treemacs--custom-tool-window)
               (lambda (kind)
                 (and (eq kind 'structure) structure-window)))
              ((symbol-function 'delete-window)
               (lambda (window)
                 (setq deleted-window window)))
              ((symbol-function 'imoogi-treemacs-hide-tool-window)
               (lambda ()
                 (setq hidden t)))
              ((symbol-function 'imoogi-treemacs--render-structure)
               (lambda (&rest _)
                 (setq rendered t)))
              ((symbol-function 'imoogi-treemacs--display-tool-buffer)
               (lambda (&rest _)
                 (setq displayed t))))
      (imoogi-treemacs-toggle-structure)
      (should (eq deleted-window structure-window))
      (should-not hidden)
      (should-not rendered)
      (should-not displayed))))

(ert-deftest imoogi-treemacs-structure-switches-from-another-tool-window ()
  (let ((hidden nil)
        (rendered nil)
        (displayed nil)
        (source-buffer (current-buffer))
        (display-kind nil))
    (cl-letf (((symbol-function 'imoogi-treemacs--custom-tool-window)
               (lambda (_kind) nil))
              ((symbol-function 'imoogi-treemacs--editor-buffer)
               (lambda () source-buffer))
              ((symbol-function 'imoogi-treemacs-hide-tool-window)
               (lambda ()
                 (setq hidden t)))
              ((symbol-function 'imoogi-treemacs--render-structure)
               (lambda (_buffer seen-source-buffer)
                 (setq rendered seen-source-buffer)))
              ((symbol-function 'imoogi-treemacs--display-tool-buffer)
               (lambda (_buffer kind)
                 (setq displayed t
                       display-kind kind))))
      (imoogi-treemacs-toggle-structure)
      (should hidden)
      (should (eq rendered source-buffer))
      (should displayed)
      (should (eq display-kind 'structure)))))

(ert-deftest imoogi-treemacs-bookmark-rendering-creates-named-buttons ()
  (let ((bookmark-alist '(("Alpha" . ((filename . "/tmp/alpha.txt")))
                          ("Beta" . ((filename . "/tmp/beta.txt"))))))
    (with-temp-buffer
      (cl-letf (((symbol-function 'bookmark-maybe-load-default-file) #'ignore)
                ((symbol-function 'bookmark-location)
                 (lambda (bookmark)
                   (alist-get 'filename (cdr bookmark)))))
        (imoogi-treemacs--render-bookmarks (current-buffer) nil))
      (should (derived-mode-p 'imoogi-treemacs-tool-window-mode))
      (should (eq (lookup-key (current-local-map) (kbd "q"))
                  #'imoogi-treemacs-hide-tool-window))
      (should (eq (lookup-key (current-local-map) (kbd "g"))
                  #'imoogi-treemacs-refresh-bookmarks))
      (goto-char (point-min))
      (let ((alpha (button-at (point))))
        (should alpha)
        (should (equal (button-label alpha) "Alpha"))
        (should (equal (button-get alpha 'imoogi-bookmark-name) "Alpha"))
        (should (eq (button-get alpha 'action)
                    #'imoogi-treemacs--bookmark-button-action)))
      (should (search-forward "Beta" nil t))
      (let ((beta (button-at (match-beginning 0))))
        (should beta)
        (should (equal (button-label beta) "Beta"))
        (should (equal (button-get beta 'imoogi-bookmark-name) "Beta"))))))

(ert-deftest imoogi-treemacs-bookmark-button-action-jumps-in-editor-window ()
  (let ((editor-window (selected-window))
        (target-buffer (get-buffer-create " *imoogi-bookmark-target*"))
        (jumped-name nil))
    (unwind-protect
        (with-temp-buffer
          (insert-text-button
           "Alpha"
           'imoogi-bookmark-name "Alpha"
           'imoogi-editor-window editor-window
           'action #'imoogi-treemacs--bookmark-button-action)
          (goto-char (point-min))
          (cl-letf (((symbol-function 'bookmark-jump)
                     (lambda (name display-function)
                       (setq jumped-name name)
                       (funcall display-function target-buffer))))
            (push-button)
            (should (equal jumped-name "Alpha"))
            (should (eq (window-buffer editor-window) target-buffer))
            (should (eq (selected-window) editor-window))))
      (when (buffer-live-p target-buffer)
        (kill-buffer target-buffer)))))

(ert-deftest imoogi-treemacs-structure-rendering-preserves-nested-imenu-labels ()
  (let ((source-buffer (get-buffer-create " *imoogi-structure-source*")))
    (unwind-protect
        (with-temp-buffer
          (cl-letf (((symbol-function 'imenu--make-index-alist)
                     (lambda (&optional _noerror)
                       '(("*Rescan*" . ignore)
                         ("Classes"
                          ("Controller"
                           ("index" . 11)
                           ("show" . 22)))
                         ("top-level" . 33)))))
            (imoogi-treemacs--render-structure (current-buffer) source-buffer))
          (should (derived-mode-p 'imoogi-treemacs-tool-window-mode))
          (should (eq imoogi-treemacs--source-buffer source-buffer))
          (should (eq (lookup-key (current-local-map) (kbd "q"))
                      #'imoogi-treemacs-hide-tool-window))
          (should (eq (lookup-key (current-local-map) (kbd "g"))
                      #'imoogi-treemacs-refresh-structure))
          (should (string-match-p "Structure" header-line-format))
          (should (string-match-p "Classes" (buffer-string)))
          (should (string-match-p "Controller" (buffer-string)))
          (should (search-forward "index" nil t))
          (let ((index-button (button-at (match-beginning 0))))
            (should index-button)
            (should (equal (button-label index-button) "index"))
            (should (eq (button-get index-button 'imoogi-source-buffer)
                        source-buffer))
            (should (equal (button-get index-button 'imoogi-imenu-item)
                           '("index" . 11))))
          (should (search-forward "show" nil t))
          (should (button-at (match-beginning 0)))
          (should (search-forward "top-level" nil t))
          (should (button-at (match-beginning 0))))
      (when (buffer-live-p source-buffer)
        (kill-buffer source-buffer)))))

(ert-deftest imoogi-treemacs-structure-rendering-shows-empty-state ()
  (let ((source-buffer (get-buffer-create " *imoogi-empty-structure-source*")))
    (unwind-protect
        (with-temp-buffer
          (cl-letf (((symbol-function 'imenu--make-index-alist)
                     (lambda (&optional _noerror)
                       '(nil ("*Rescan*" . -99)))))
            (imoogi-treemacs--render-structure (current-buffer) source-buffer))
          (should (string-match-p "Structure 정보가 없습니다" (buffer-string))))
      (when (buffer-live-p source-buffer)
        (kill-buffer source-buffer)))))

(ert-deftest imoogi-treemacs-custom-window-ignores-a-reused-stale-slot ()
  (let ((bookmarks-buffer
         (get-buffer-create imoogi-treemacs-bookmarks-buffer-name))
        (replacement-buffer (get-buffer-create " *imoogi-reused-tool-slot*")))
    (unwind-protect
        (save-window-excursion
          (delete-other-windows)
          (let ((window
                 (display-buffer-in-side-window
                  bookmarks-buffer
                  '((side . left)
                    (slot . -1)
                    (window-parameters
                     . ((imoogi-treemacs-tool-window . bookmarks)))))))
            (should (eq (imoogi-treemacs--custom-tool-window 'bookmarks) window))
            (set-window-buffer window replacement-buffer)
            (should-not (imoogi-treemacs--custom-tool-window 'bookmarks))))
      (dolist (buffer (list bookmarks-buffer replacement-buffer))
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

(ert-deftest imoogi-treemacs-structure-button-action-uses-source-buffer-and-imenu ()
  (let ((source-buffer (get-buffer-create " *imoogi-structure-action-source*"))
        (editor-window (selected-window))
        (seen-item nil)
        (recentered nil))
    (unwind-protect
        (with-temp-buffer
          (insert-text-button
           "index"
           'imoogi-source-buffer source-buffer
           'imoogi-editor-window editor-window
           'imoogi-imenu-item '("index" . 11)
           'action #'imoogi-treemacs--structure-button-action)
          (goto-char (point-min))
          (cl-letf (((symbol-function 'imenu)
                     (lambda (item)
                       (setq seen-item item)))
                    ((symbol-function 'recenter)
                     (lambda (&optional _arg)
                       (setq recentered t))))
            (push-button)
            (should (eq (selected-window) editor-window))
            (should (eq (current-buffer) source-buffer))
            (should (equal seen-item '("index" . 11)))
            (should recentered)))
      (when (buffer-live-p source-buffer)
        (kill-buffer source-buffer)))))

(ert-deftest imoogi-treemacs-tool-windows-share-one-left-side-slot ()
  (let ((source-buffer (get-buffer-create " *imoogi-tool-window-source*"))
        (bookmark-alist nil))
    (unwind-protect
        (save-window-excursion
          (delete-other-windows)
          (set-window-buffer (selected-window) source-buffer)
          (with-current-buffer source-buffer
            (emacs-lisp-mode)
            (erase-buffer)
            (insert "(defun alpha () nil)\n"))
          (cl-letf (((symbol-function 'bookmark-maybe-load-default-file)
                     #'ignore))
            (imoogi-treemacs-toggle-bookmarks))
          (should (imoogi-treemacs--custom-tool-window 'bookmarks))

          (imoogi-treemacs-toggle-structure)
          (should-not (imoogi-treemacs--custom-tool-window 'bookmarks))
          (should (imoogi-treemacs--custom-tool-window 'structure))
          (with-current-buffer imoogi-treemacs-structure-buffer-name
            (should (string-match-p "alpha" (buffer-string))))

          (imoogi-treemacs-toggle-structure)
          (should-not (imoogi-treemacs--custom-tool-window 'structure)))
      (dolist (buffer (list source-buffer
                            (get-buffer imoogi-treemacs-bookmarks-buffer-name)
                            (get-buffer imoogi-treemacs-structure-buffer-name)))
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

;;; treemacs-tool-window-test.el ends here
