;;; workspace-bridge-test.el --- Project/Perspective workspace tests -*- lexical-binding: t; -*-

;;; Code:

(require 'cl-lib)
(require 'consult)
(require 'ert)
(require 'project)

(defun imoogi-test--root (name)
  (file-name-as-directory
   (expand-file-name name (make-temp-file "imoogi-project-root-" t))))

(defun imoogi-test--project (root)
  (list 'transient (file-truename root)))

(cl-defmethod project-root ((project (head transient)))
  (cadr project))

(defmacro imoogi-test--with-project-command-stubs (root &rest body)
  (declare (indent 1))
  `(let* ((imoogi-project-perspective-alist nil)
          (imoogi-test--prompter-called nil)
         (project-prompter
          (lambda ()
            (setq imoogi-test--prompter-called t)
            (file-truename ,root)))
         (imoogi-test--current-perspective "scratch")
         (imoogi-test--remembered nil)
         (imoogi-test--switched nil)
         (imoogi-test--dired nil)
         (current-prefix-arg nil))
     (cl-letf (((symbol-function 'project-current)
                (lambda (&optional _maybe-prompt directory)
                  (list 'transient (file-truename (or directory ,root)))))
               ((symbol-function 'project-remember-project)
                (lambda (project)
                  (setq imoogi-test--remembered project)))
               ((symbol-function 'project-known-project-roots)
                (lambda () (list (file-truename ,root))))
               ((symbol-function 'project-dired)
                (lambda ()
                  (setq imoogi-test--dired imoogi-test--current-perspective)))
               ((symbol-function 'persp-current-name)
                (lambda () imoogi-test--current-perspective))
               ((symbol-function 'persp-switch)
                (lambda (name)
                  (setq imoogi-test--current-perspective name
                        imoogi-test--switched name))))
       ,@body)))

(ert-deftest imoogi-project-switch-perspective-is-bound-at-C-x-p-p ()
  (should (fboundp 'imoogi-project-switch-perspective))
  (should (eq (lookup-key project-prefix-map (kbd "p"))
              #'imoogi-project-switch-perspective))
  (should-not (eq (lookup-key project-prefix-map (kbd "p"))
                  #'project-switch-project)))

(ert-deftest imoogi-perspective-last-workspace-is-bound-at-C-x-x-l ()
  (should (eq (lookup-key perspective-map (kbd "l"))
              #'persp-switch-last)))

(ert-deftest imoogi-project-switch-perspective-remembers-project-and-opens-default-workspace ()
  (let ((root (imoogi-test--root "alpha")))
    (imoogi-test--with-project-command-stubs root
      (call-interactively #'imoogi-project-switch-perspective)
      (should imoogi-test--prompter-called)
      (should (equal (project-root imoogi-test--remembered) (file-truename root)))
      (should (equal imoogi-test--switched "alpha"))
      (should (equal imoogi-test--dired "alpha")))))

(ert-deftest imoogi-project-switch-perspective-with-prefix-keeps-current-workspace ()
  (let ((root (imoogi-test--root "beta")))
    (imoogi-test--with-project-command-stubs root
      (let ((current-prefix-arg '(4)))
        (call-interactively #'imoogi-project-switch-perspective))
      (should (equal (project-root imoogi-test--remembered) (file-truename root)))
      (should-not imoogi-test--switched)
      (should (equal imoogi-test--dired "scratch")))))

(ert-deftest imoogi-project-perspective-registry-freezes-existing-name ()
  (let* ((root (imoogi-test--root "gamma"))
         (canonical (file-truename root)))
    (imoogi-test--with-project-command-stubs root
      (setq imoogi-project-perspective-alist `((,canonical . "kept-name")))
      (call-interactively #'imoogi-project-switch-perspective)
      (should (equal imoogi-test--switched "kept-name"))
      (should (equal (cdr (assoc canonical imoogi-project-perspective-alist))
                     "kept-name")))))

(ert-deftest imoogi-project-perspective-registry-keeps-name-when-known-roots-grow-and-shrink ()
  (let* ((root (imoogi-test--root "stable"))
         (other-parent (make-temp-file "imoogi-other-parent-" t))
         (other-root (file-name-as-directory (expand-file-name "stable" other-parent)))
         (canonical (file-truename root))
         (canonical-other nil)
         (known-roots nil)
         (imoogi-project-perspective-alist nil))
    (make-directory other-root t)
    (setq canonical-other (file-truename other-root)
          known-roots (list canonical))
    (cl-letf (((symbol-function 'project-known-project-roots)
               (lambda () known-roots)))
      (let ((initial-name (imoogi-project-perspective-name canonical)))
        (setq known-roots (list canonical canonical-other))
        (should (equal (imoogi-project-perspective-name canonical)
                       initial-name))
        (setq known-roots nil)
        (should (equal (imoogi-project-perspective-name canonical)
                       initial-name))
        (should (equal imoogi-project-perspective-alist
                       `((,canonical . ,initial-name))))))))

(ert-deftest imoogi-project-perspective-registry-adds-secure-hash-when-name-belongs-to-another-root ()
  (let* ((root (imoogi-test--root "delta"))
         (other-root (imoogi-test--root "other-delta"))
         (canonical (file-truename root))
         (canonical-other (file-truename other-root))
         (imoogi-project-perspective-alist `((,canonical-other . "delta"))))
    (cl-letf (((symbol-function 'project-known-project-roots)
               (lambda () (list canonical canonical-other))))
      (let ((name (imoogi-project-perspective-name canonical)))
        (should (equal name
                       (format "delta--%s"
                               (substring (secure-hash 'sha1 canonical) 0 8))))
        (should (equal (cdr (assoc canonical imoogi-project-perspective-alist))
                       name))
        (should (equal (cdr (assoc canonical-other imoogi-project-perspective-alist))
                       "delta"))))))

(ert-deftest imoogi-project-perspective-registry-distinguishes-same-basename-roots ()
  (let* ((parent-a (make-temp-file "imoogi-parent-a-" t))
         (parent-b (make-temp-file "imoogi-parent-b-" t))
         (root-a (file-name-as-directory (expand-file-name "shared" parent-a)))
         (root-b (file-name-as-directory (expand-file-name "shared" parent-b))))
    (make-directory root-a t)
    (make-directory root-b t)
    (let ((canonical-a (file-truename root-a))
          (canonical-b (file-truename root-b))
          (imoogi-project-perspective-alist nil)
          (imoogi-test--current-perspective "scratch")
          (project-prompter
           (let ((roots (list root-a root-b)))
             (lambda ()
               (file-truename (pop roots)))))
          (imoogi-test--switches nil))
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&optional _maybe-prompt directory)
                   (list 'transient (file-truename (or directory root-a)))))
                ((symbol-function 'project-remember-project) #'ignore)
                ((symbol-function 'project-known-project-roots)
                 (lambda () (list canonical-a canonical-b)))
                ((symbol-function 'project-dired) #'ignore)
                ((symbol-function 'persp-switch)
                 (lambda (name) (push name imoogi-test--switches))))
        (call-interactively #'imoogi-project-switch-perspective)
        (call-interactively #'imoogi-project-switch-perspective)
        (should (= (length imoogi-project-perspective-alist) 2))
        (should-not (equal (cdr (assoc canonical-a imoogi-project-perspective-alist))
                           (cdr (assoc canonical-b imoogi-project-perspective-alist))))
        (should (= (length (delete-dups (copy-sequence imoogi-test--switches))) 2))))))

(ert-deftest imoogi-project-perspective-registry-round-trips-through-savehist-variable-list ()
  (require 'savehist)
  (should (boundp 'imoogi-project-perspective-alist))
  (should (memq 'imoogi-project-perspective-alist savehist-additional-variables)))

(ert-deftest imoogi-consult-perspective-buffer-is-bound-at-C-x-b ()
  (should (fboundp 'imoogi-consult-perspective-buffer))
  (should (eq (lookup-key ctl-x-map (kbd "b"))
              #'imoogi-consult-perspective-buffer)))

(ert-deftest imoogi-consult-perspective-buffer-default-uses-current-perspective-buffers-only ()
  (should (fboundp 'imoogi-consult-perspective-buffer))
  (let ((imoogi-test--consult-called nil)
        (imoogi-test--seen-buffer-list-function nil)
        (imoogi-test--seen-sources nil)
        (current-prefix-arg nil))
    (cl-letf (((symbol-function 'persp-current-buffers*)
               (lambda (&optional include-shared)
                 (should include-shared)
                 (list (get-buffer-create "current-persp-buffer"))))
              ((symbol-function 'consult-buffer)
               (lambda (&optional sources)
                 (setq imoogi-test--consult-called t
                       imoogi-test--seen-buffer-list-function consult-buffer-list-function
                       imoogi-test--seen-sources sources))))
      (call-interactively #'imoogi-consult-perspective-buffer)
      (should imoogi-test--consult-called)
      (should (functionp imoogi-test--seen-buffer-list-function))
      (should (equal (funcall imoogi-test--seen-buffer-list-function)
                     (list (get-buffer-create "current-persp-buffer"))))
      (should (equal imoogi-test--seen-sources (list consult-source-buffer))))))

(ert-deftest imoogi-consult-perspective-buffer-default-does-not-leak-global-sources ()
  (should (fboundp 'imoogi-consult-perspective-buffer))
  (let ((current-prefix-arg nil)
        (imoogi-test--seen-sources :unset))
    (cl-letf (((symbol-function 'persp-current-buffers*)
               (lambda (&optional _include-shared) nil))
              ((symbol-function 'consult-buffer)
               (lambda (&optional sources)
                 (setq imoogi-test--seen-sources sources))))
      (call-interactively #'imoogi-consult-perspective-buffer)
      (dolist (source (list 'consult-source-hidden-buffer
                            'consult-source-modified-buffer
                            'consult-source-recent-file
                            'consult-source-bookmark
                            'consult-source-project-buffer
                            'consult-source-project-recent-file))
        (should-not (memq source imoogi-test--seen-sources))))))

(ert-deftest imoogi-consult-perspective-buffer-prefix-uses-full-consult-buffer ()
  (should (fboundp 'imoogi-consult-perspective-buffer))
  (let ((current-prefix-arg '(4))
        (imoogi-test--seen-sources :unset))
    (cl-letf (((symbol-function 'consult-buffer)
               (lambda (&optional sources)
                 (setq imoogi-test--seen-sources sources))))
      (call-interactively #'imoogi-consult-perspective-buffer)
      (should (null imoogi-test--seen-sources)))))

(ert-deftest imoogi-perspective-state-path-lives-under-user-cache-directory ()
  (should (boundp 'imoogi-perspective-state-file))
  (should (equal imoogi-perspective-state-file
                 (locate-user-emacs-file ".cache/perspective-state.el"))))

(ert-deftest imoogi-perspective-restore-missing-file-is-nonfatal ()
  (should (fboundp 'imoogi-perspective-state-restore))
  (let ((imoogi-perspective-state-file
         (expand-file-name "missing-perspective-state.el"
                           (make-temp-file "imoogi-persp-state-" t))))
    (should-not (file-exists-p imoogi-perspective-state-file))
    (should-not (imoogi-perspective-state-restore))))

(ert-deftest imoogi-perspective-restore-corrupt-file-is-nonfatal ()
  (should (fboundp 'imoogi-perspective-state-restore))
  (let* ((dir (make-temp-file "imoogi-persp-state-" t))
         (imoogi-perspective-state-file (expand-file-name "state.el" dir))
         (called nil))
    (with-temp-file imoogi-perspective-state-file
      (insert "not perspective state"))
    (cl-letf (((symbol-function 'persp-state-load)
               (lambda (_file)
                 (setq called t)
                 (error "corrupt state"))))
      (should-not (imoogi-perspective-state-restore))
      (should called))))

(ert-deftest imoogi-perspective-save-state-creates-cache-directory ()
  (should (fboundp 'imoogi-perspective-state-save))
  (let* ((dir (make-temp-file "imoogi-persp-state-" t))
         (imoogi-perspective-state-file (expand-file-name ".cache/perspective-state.el" dir))
         (saved-file nil))
    (cl-letf (((symbol-function 'persp-state-save)
               (lambda (file)
                 (setq saved-file file)
                 (with-temp-file file (insert "state")))))
      (imoogi-perspective-state-save)
      (should (file-directory-p (file-name-directory imoogi-perspective-state-file)))
      (should (equal saved-file imoogi-perspective-state-file))
      (should (file-exists-p imoogi-perspective-state-file)))))

(ert-deftest imoogi-perspective-state-serialization-keeps-file-and-dired-buffers-only ()
  (require 'dired)
  (require 'perspective)
  (let* ((dir (make-temp-file "imoogi-persp-serialize-" t))
         (file (expand-file-name "note.txt" dir))
         (file-buffer nil)
         (dired-buffer nil)
         (transient-buffer (generate-new-buffer "*imoogi-transient*")))
    (with-temp-file file
      (insert "stateful"))
    (unwind-protect
        (progn
          (setq file-buffer (find-file-noselect file)
                dired-buffer (dired-noselect dir))
          (with-current-buffer transient-buffer
            (setq major-mode 'comint-mode))
          (should (persp--state-interesting-buffer-p file-buffer))
          (should (persp--state-interesting-buffer-p dired-buffer))
          (should-not (persp--state-interesting-buffer-p transient-buffer))
          (let ((state-files (persp--state-file-data)))
            (should (member (file-truename file) state-files))
            (should (member (file-name-as-directory (file-truename dir))
                            state-files))
            (should-not (member (buffer-name transient-buffer) state-files))))
      (mapc (lambda (buffer)
              (when (buffer-live-p buffer)
                (kill-buffer buffer)))
            (list file-buffer dired-buffer transient-buffer)))))

(ert-deftest imoogi-perspective-state-window-serialization-replaces-transient-buffer-with-scratch ()
  (require 'perspective)
  (let* ((window-state '(leaf (buffer "transient-buffer") (point 1)))
         (massaged (persp--state-window-state-massage
                    window-state "workspace" '("file-buffer"))))
    (should (equal massaged
                   `(leaf (buffer ,(persp-scratch-buffer "workspace"))
                          (point 1))))))

(ert-deftest imoogi-treemacs-project-binding-uses-project-el-command ()
  (should (eq (lookup-key global-map (kbd "C-x t p"))
              #'treemacs-add-and-display-current-project)))

(ert-deftest imoogi-treemacs-does-not-auto-start-on-emacs-startup-hook ()
  "Treemacs no longer opens itself on startup — only via manual toggle."
  (let ((hooks (mapcar (lambda (entry) (if (consp entry) (car entry) entry))
                       emacs-startup-hook)))
    (should (equal hooks '(imoogi-perspective-state-restore)))
    (should-not (memq 'treemacs hooks))
    (should-not (fboundp 'imoogi-treemacs-start))))

;;; workspace-bridge-test.el ends here
