// Package media is the media pass design.md §9 describes: rendered field
// HTML in, rewritten field HTML plus a list of files to upload out
// (spec.md REQ-C-012 … REQ-C-015).
//
// It performs read-only local I/O — it reads each referenced file's bytes to
// compute a content hash — and no network call of any kind. The stored
// filename is therefore computed entirely client-side, which is what lets
// the rewrite AND the content hash both complete before any AnkiConnect
// request is issued (REQ-C-016). Issuing the uploads is the planner's job,
// gated on the add/update paths (REQ-C-014).
package media

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"html"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Upload names one local file to place in Anki's media collection.
// Filename is the stored name design.md §9.3 fixes; Path is the absolute,
// confinement-checked local path the file was read from.
type Upload struct {
	Filename string
	Path     string
}

// NotFoundError reports a local media reference that could not be turned
// into an upload: it did not resolve, it escaped the sync root, or it could
// not be read. The planner maps it to protocol.CodeMediaFileNotFound and
// skips the entry (REQ-C-015).
type NotFoundError struct {
	// Reference is the reference exactly as it appeared in the field text.
	Reference string
	// Reason is machine-oriented detail; the front end's own code-to-message
	// table, not this string, is what reaches the user (plan.md D-5).
	Reason string
}

func (e *NotFoundError) Error() string {
	return fmt.Sprintf("media reference %q is unusable: %s", e.Reference, e.Reason)
}

// imageExtension mirrors go-org's OWN image extension set, verbatim from
// go-org v1.9.1 org/inline.go:68. Mirrored rather than extended on purpose
// (design.md §9.4): go-org decides the one-part case and this package
// decides the two-part case, so an extension recognized here but not there
// would make [[file:x.avif]] an anchor and [[file:x.avif][d]] an image —
// the same file behaving differently for a reason no user could infer.
var imageExtension = regexp.MustCompile(`(?i)^[.](png|gif|jpe?g|svg|tiff?|webp|x[bp]m|p[bgpn]m)$`)

// The rendered HTML this pass walks is machine-generated by go-org's HTML
// writer, so its tag shapes are fixed and known rather than arbitrary. That
// is what makes pattern matching adequate here — and it is why the
// org-preview asset resolver's LINK regex is deliberately not reused
// (design.md §9.2): that regex belongs to a different parser.
var (
	anchorPattern = regexp.MustCompile(`(?s)<a href="([^"]*)">(.*?)</a>`)
	imgPattern    = regexp.MustCompile(`(?s)<img\b[^>]*>`)
	srcAttr       = regexp.MustCompile(`\bsrc="([^"]*)"`)
	anyTag        = regexp.MustCompile(`(?s)<[^>]*>`)
	// A URI scheme needs two or more characters before the colon, so a
	// single-letter Windows drive prefix (C:\...) is not mistaken for one.
	schemePrefix = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9+.\-]+:`)
	disallowed   = regexp.MustCompile(`[^a-z0-9_-]+`)
	dashRuns     = regexp.MustCompile(`-{2,}`)
)

// Rewrite applies the media pass to one entry's rendered fields.
//
// baseDir is the directory of the entry's own Org file — references resolve
// against it, not against root and not against the process working
// directory (REQ-C-012.2). root is the sync root every resolved path is
// confined to.
//
// design.md §9.1 sketches the entry point as (baseDir, renderedFields);
// root is a third parameter because confinement needs a root to confine to
// and this package holds no configuration of its own.
//
// The returned map is a fresh copy — the caller's map is never mutated.
// The returned uploads are deduplicated by stored name within this entry
// and ordered deterministically (fields visited in sorted name order, then
// in document order), so a caller may compare two runs' upload lists.
//
// A single unusable local reference fails the whole entry with a
// *NotFoundError: REQ-C-015 makes such an entry a skip, and a partially
// rewritten field would otherwise be hashed and sent as though it were
// complete.
func Rewrite(baseDir, root string, fields map[string]string) (map[string]string, []Upload, error) {
	canonRoot, err := canonical(root)
	if err != nil {
		return nil, nil, &NotFoundError{Reference: root, Reason: "sync root cannot be canonicalized: " + err.Error()}
	}

	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)

	out := make(map[string]string, len(fields))
	seen := make(map[string]bool)
	var uploads []Upload

	for _, name := range names {
		text, found, err := rewriteField(baseDir, canonRoot, fields[name])
		if err != nil {
			return nil, nil, err
		}
		out[name] = text
		for _, u := range found {
			if seen[u.Filename] {
				continue
			}
			seen[u.Filename] = true
			uploads = append(uploads, u)
		}
	}
	return out, uploads, nil
}

// rewriteField runs the two rules over one field's HTML, in the order
// REQ-C-012.1 fixes: the two-part anchor becomes an img FIRST, and is then
// resolved and rewritten exactly as a one-part reference would be.
func rewriteField(baseDir, canonRoot, text string) (string, []Upload, error) {
	var firstErr error
	var uploads []Upload

	// Rule 1 (REQ-C-012.1): an anchor whose target carries an extension in
	// go-org's image set becomes an img carrying the link description as
	// alt text. Remote targets are excluded here rather than converted —
	// REQ-C-013.1 forbids disturbing them at all.
	text = anchorPattern.ReplaceAllStringFunc(text, func(match string) string {
		parts := anchorPattern.FindStringSubmatch(match)
		href, description := parts[1], parts[2]
		if href == "" || isRemote(href) || !imageExtension.MatchString(path.Ext(href)) {
			return match
		}
		return `<img src="` + href + `" alt="` + altText(description) + `" />`
	})

	// Rule 2 (REQ-C-012.2, REQ-C-012.3): every img with a local src is
	// resolved, confined, hashed, and its src rewritten to the stored name.
	// go-org's own alt and title attributes are left alone — REQ-C-012.3
	// names the src attribute and only the src attribute.
	text = imgPattern.ReplaceAllStringFunc(text, func(tag string) string {
		if firstErr != nil {
			return tag
		}
		m := srcAttr.FindStringSubmatch(tag)
		if m == nil {
			return tag
		}
		ref := m[1]
		if ref == "" || isRemote(ref) {
			return tag
		}
		stored, abs, err := resolve(baseDir, canonRoot, ref)
		if err != nil {
			firstErr = err
			return tag
		}
		uploads = append(uploads, Upload{Filename: stored, Path: abs})
		return strings.Replace(tag, `src="`+ref+`"`, `src="`+stored+`"`, 1)
	})

	if firstErr != nil {
		return "", nil, firstErr
	}
	return text, uploads, nil
}

// resolve turns one reference into its stored name and absolute path,
// reusing the org-preview asset resolver's LOGIC (design.md §9.2):
// URL-unescape, join against the base directory, canonicalize with
// absolute-path plus symlink evaluation tolerating a non-existent tail, and
// confine to the allowed root.
func resolve(baseDir, canonRoot, ref string) (storedFilename, absPath string, err error) {
	// Attribute values arrive HTML-encoded (&amp; for &), and Org link
	// targets arrive percent-encoded (%20 for a space); both layers come
	// off before the path is touched.
	//
	// An undecodable percent sequence is NOT an error: "100%.png" is a legal
	// filename on every filesystem this runs on, and Org does not require a
	// link target to be percent-encoded, so a stray "%" means "a literal
	// percent" far more often than it means "a malformed escape". The raw
	// reference is used instead. Confinement is unaffected — canonicalization
	// and the root check still run below.
	decoded := html.UnescapeString(ref)
	if unescaped, unescapeErr := url.PathUnescape(decoded); unescapeErr == nil {
		decoded = unescaped
	}

	candidate := filepath.FromSlash(decoded)
	if !filepath.IsAbs(candidate) {
		candidate = filepath.Join(baseDir, candidate)
	}

	clean, canonErr := canonical(candidate)
	if canonErr != nil {
		return "", "", &NotFoundError{Reference: ref, Reason: "path cannot be canonicalized: " + canonErr.Error()}
	}
	if !within(canonRoot, clean) {
		return "", "", &NotFoundError{Reference: ref, Reason: "resolved path lies outside the sync root"}
	}

	content, readErr := os.ReadFile(clean)
	if readErr != nil {
		reason := "file cannot be read"
		if errors.Is(readErr, os.ErrNotExist) {
			reason = "no such file"
		}
		return "", "", &NotFoundError{Reference: ref, Reason: reason + ": " + readErr.Error()}
	}

	return storedName(decoded, content), clean, nil
}

// storedName implements design.md §9.3: a sanitized basename, the separator
// "-", and the first 12 lowercase hex characters of the file content's
// SHA-256, inserted BEFORE the lowercased original extension —
// diagram.png -> diagram-3f9a1c2b8e40.png.
//
// Twelve hex characters is 48 bits, which makes an accidental collision
// across a personal collection's media set negligible while keeping the
// name readable in Anki's media browser. Because the digest is over the
// file's CONTENT, two same-named images in different directories get
// different stored names, and the same image referenced from two entries
// gets one.
func storedName(reference string, content []byte) string {
	base := path.Base(filepath.ToSlash(reference))
	ext := path.Ext(base)
	sum := sha256.Sum256(content)
	return sanitizeBasename(strings.TrimSuffix(base, ext)) + "-" + hex.EncodeToString(sum[:])[:12] + strings.ToLower(ext)
}

// sanitizeBasename applies design.md §9.3's sanitization: lowercase, every
// character outside [a-z0-9_-] replaced by "-", "-" runs collapsed to one,
// leading and trailing separators stripped, an empty result replaced by
// "img".
//
// The edge strip covers "_" as well as "-", which §9.3's table does not
// name. That is REQ-C-013.2 being enforced where it can be: Anki reads a
// leading "_" as "exempt from Check Media", which would exempt imoogi's own
// uploads from the very cleanup that keeps orphan media out of this SPEC's
// scope. An underscore INSIDE the name is untouched.
func sanitizeBasename(s string) string {
	s = strings.ToLower(s)
	s = disallowed.ReplaceAllString(s, "-")
	s = dashRuns.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-_")
	if s == "" {
		return "img"
	}
	return s
}

// altText turns an anchor's inner HTML into an attribute-safe alt value.
// Inline markup go-org emitted inside the link (<strong>, <code>) cannot
// live in an attribute, so it is stripped; the text is then decoded and
// re-encoded so the result is well-formed however the input was encoded.
func altText(inner string) string {
	return html.EscapeString(html.UnescapeString(anyTag.ReplaceAllString(inner, "")))
}

// isRemote reports whether a reference carries a URI scheme, which
// REQ-C-013.1 places entirely out of this pass's reach.
func isRemote(ref string) bool {
	return schemePrefix.MatchString(ref)
}

// canonical resolves a path to its absolute, symlink-evaluated form,
// tolerating a non-existent tail so a missing file is reported as a missing
// file rather than as a canonicalization failure.
func canonical(p string) (string, error) {
	abs, err := filepath.Abs(p)
	if err != nil {
		return "", err
	}
	eval, err := filepath.EvalSymlinks(abs)
	if err != nil {
		if os.IsNotExist(err) {
			return filepath.Clean(abs), nil
		}
		return "", err
	}
	return filepath.Clean(eval), nil
}

// within reports whether candidate lies at or below root. Both are expected
// to be canonical already.
func within(root, candidate string) bool {
	rel, err := filepath.Rel(root, candidate)
	if err != nil {
		return false
	}
	return rel == "." || (rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)))
}
